import { useEffect, useState } from 'react';
import { Comparison, getMetricsEvidence, MetricsEvidence, Task } from './api';
import { Locale, TextKey } from './locales';
import { MetricCard, MetricSparkline } from './MetricsTimeline';

type Translate = (key: TextKey, values?: Record<string, string | number>) => string;

export function DiffMetricsEvidencePanel({ comparison, tasks, locale, t }: { comparison: Comparison | null; tasks: Task[]; locale: Locale; t: Translate }) {
  const completed = tasks.filter((task) => task.inputType === 'metrics' && task.status === 'completed'); const [taskId, setTaskId] = useState(''); const [evidence, setEvidence] = useState<MetricsEvidence | null>(null); const [error, setError] = useState('');
  useEffect(() => { if (!comparison || !taskId) { setEvidence(null); return; } let active = true; getMetricsEvidence(comparison.diffId, taskId).then((result) => { if (active) { setEvidence(result); setError(''); } }).catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : t('metricsEvidence.loadFailed')); }); return () => { active = false; }; }, [comparison, taskId, t]);
  if (!comparison) return null;
  return <section className="evidence-panel"><h3>{t('metricsEvidence.title')}</h3><label>{t('metricsEvidence.select')}<select value={taskId} onChange={(event) => setTaskId(event.target.value)}><option value="">{completed.length ? t('metricsEvidence.select') : t('metricsEvidence.none')}</option>{completed.map((task) => <option key={task.taskId} value={task.taskId}>{task.name} · {task.sha256.slice(0, 12)}</option>)}</select></label>{error && <p role="alert">{error}</p>}{evidence && <><p className="notice">{t('metricsEvidence.sourceUnverified')} {t('metricsEvidence.causality')} {t('metricsEvidence.counterGap')} {t('metricsEvidence.reclaimableCaveat')}</p><div className="metrics"><EvidenceValue label={t('metricsEvidence.growthStart')} value={evidence.growthStartedAt ? new Date(evidence.growthStartedAt).toLocaleString(locale === 'zh' ? 'zh-CN' : 'en-US') : '—'} /><MetricCard locale={locale} metricKey="metrics.dbDelta" value={bytes(evidence.dbTotalDeltaBytes)} /><MetricCard locale={locale} metricKey="metrics.inUseDelta" value={bytes(evidence.dbInUseDeltaBytes)} /><MetricCard locale={locale} metricKey="metrics.reclaimable" value={bytes(evidence.maxDefragReclaimableBytes)} /><MetricCard locale={locale} metricKey="metrics.quotaRatio" value={`${(evidence.quotaPeakRatio * 100).toFixed(1)}%`} /><MetricCard locale={locale} metricKey="metrics.putRate" value={`${evidence.peakPutRate.value.toFixed(2)} · ${evidence.putTemporallyAligned ? t('metricsEvidence.aligned') : t('metricsEvidence.notAligned')}`} /><MetricCard locale={locale} metricKey="metrics.deleteRate" value={`${evidence.peakDeleteRate.value.toFixed(2)} · ${evidence.deleteTemporallyAligned ? t('metricsEvidence.aligned') : t('metricsEvidence.notAligned')}`} /><MetricCard locale={locale} metricKey="metrics.backendP99" value={`${evidence.backendCommitP99.value.toFixed(3)} s`} /><MetricCard locale={locale} metricKey="metrics.walP99" value={`${evidence.walFsyncP99.value.toFixed(3)} s`} /></div>{evidence.largestGrowthInterval && <p>{t('metricsEvidence.growthInterval')}: {new Date(evidence.largestGrowthInterval.from).toLocaleString()} → {new Date(evidence.largestGrowthInterval.to).toLocaleString()} · {bytes(evidence.largestGrowthInterval.deltaBytes)}</p>}<div className="curve-grid">{evidence.curves.map((curve) => <figure key={curve.metricType}><figcaption>{curve.metricType}</figcaption><MetricSparkline curve={curve} /></figure>)}</div></>}</section>;
}

function EvidenceValue({ label, value }: { label: string; value: string }) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article>; }
function bytes(value: number) { const absolute = Math.abs(value); if (absolute < 1024) return `${value} B`; if (absolute < 1024 ** 2) return `${(value / 1024).toFixed(1)} KiB`; if (absolute < 1024 ** 3) return `${(value / 1024 ** 2).toFixed(1)} MiB`; return `${(value / 1024 ** 3).toFixed(1)} GiB`; }
