import { useEffect, useState } from 'react';
import { getMetricsTimeline, MetricCurve, MetricType, MetricsTimeline, Task } from './api';
import { Locale, metric, MetricKey, TextKey } from './locales';

type Translate = (key: TextKey, values?: Record<string, string | number>) => string;
const types: MetricType[] = ['db_total_bytes', 'db_in_use_bytes', 'quota_bytes', 'put_total', 'delete_total', 'backend_commit_seconds', 'wal_fsync_seconds'];

export function MetricSparkline({ curve }: { curve: MetricCurve }) {
  if (curve.points.length < 2) return <p className="empty">{curve.points[0]?.value ?? '—'}</p>;
  const values = curve.points.map((point) => point.value);
  const minimum = Math.min(...values); const maximum = Math.max(...values); const range = maximum - minimum || 1;
  const path = curve.points.map((point, index) => `${index ? 'L' : 'M'} ${(index / (curve.points.length - 1) * 100).toFixed(2)} ${(40 - (point.value - minimum) / range * 36).toFixed(2)}`).join(' ');
  return <svg className="metric-curve" viewBox="0 0 100 44" role="img" aria-label={`${curve.metricType}: ${minimum}–${maximum}`}><title>{curve.metricType}: {minimum}–{maximum}</title><path d={path} /></svg>;
}

export function MetricsTimelineAnalysis({ task, locale, t, onClose }: { task: Task; locale: Locale; t: Translate; onClose: () => void }) {
  const [timeline, setTimeline] = useState<MetricsTimeline | null>(null); const [metricType, setMetricType] = useState<MetricType | ''>(''); const [instance, setInstance] = useState(''); const [page, setPage] = useState(1); const [error, setError] = useState('');
  useEffect(() => { let active = true; getMetricsTimeline(task.taskId, { metricType, instance, page, pageSize: 20 }).then((result) => { if (active) { setTimeline(result); setError(''); } }).catch((reason: unknown) => { if (active) setError(reason instanceof Error ? reason.message : t('metrics.loadFailed')); }); return () => { active = false; }; }, [task.taskId, metricType, instance, page, t]);
  return <section className="panel analysis"><div className="section-title"><h2>{t('metrics.title')}</h2><button onClick={onClose}>{t('actions.close')}</button></div><p><strong>{task.name}</strong> · <code>{task.sha256}</code></p>{error && <p role="alert">{error}</p>}{timeline && <><div className="metrics metric-summary"><MetricCard locale={locale} metricKey="metrics.supportedSeries" value={String(timeline.summary.supportedSeries)} /><MetricCard locale={locale} metricKey="metrics.validSamples" value={String(timeline.summary.validSamples)} /><MetricCard locale={locale} metricKey="metrics.instances" value={String(timeline.summary.instanceCount)} /></div><div className="filters"><label>{t('metrics.allTypes')}<select value={metricType} onChange={(event) => { setMetricType(event.target.value as MetricType | ''); setPage(1); }}><option value="">{t('metrics.allTypes')}</option>{types.map((type) => <option key={type}>{type}</option>)}</select></label><label>{t('metrics.instance')}<input value={instance} onChange={(event) => { setInstance(event.target.value); setPage(1); }} /></label></div><div className="curve-grid">{timeline.curves.map((curve) => <figure key={curve.metricType}><figcaption>{curve.metricType}</figcaption><MetricSparkline curve={curve} /></figure>)}</div><div className="table-wrap"><table><thead><tr><th>{t('metrics.instance')}</th><th>{t('metrics.series')}</th><th>{t('metrics.samples')}</th></tr></thead><tbody>{timeline.series.map((item) => <tr key={item.series.seriesHash}><td>{item.series.instance || '—'}</td><td><code>{item.series.sourceMetricName}</code></td><td>{item.samples.length}</td></tr>)}{timeline.series.length === 0 && <tr><td colSpan={3} className="empty">{t('metrics.empty')}</td></tr>}</tbody></table></div><div className="pager"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>{t('pagination.previous')}</button><span>{t('pagination.records', { page, count: timeline.total })}</span><button disabled={page * timeline.pageSize >= timeline.total} onClick={() => setPage((value) => value + 1)}>{t('pagination.next')}</button></div><small>{new Date(timeline.summary.firstObservedAt ?? task.createdAt).toLocaleString(locale === 'zh' ? 'zh-CN' : 'en-US')} → {new Date(timeline.summary.lastObservedAt ?? task.createdAt).toLocaleString(locale === 'zh' ? 'zh-CN' : 'en-US')}</small></>}</section>;
}

export function MetricCard({ locale, metricKey, value }: { locale: Locale; metricKey: MetricKey; value: string }) { const copy = metric(locale, metricKey); return <article className="metric"><span className="metric-label">{copy.label}<span className="metric-help" role="img" aria-label={copy.help} title={copy.help} tabIndex={0}>?</span></span><strong>{value}</strong></article>; }
